#!/usr/bin/env bash

# Use first param as our serverConfigFile, defaulting to Lucee 5.
serverConfigFile=${1:-server-lucee@5.json}

# Start server, passing in environment variables from .env file
cat .env | xargs -J % env % box server start serverConfigFile="$serverConfigFile"
