#!/usr/bin/env bash

# Use first param as our serverConfigFile, defaulting to Lucee 5.
serverConfigFile=${1:-server-lucee@5.json}

# Start server. Environment variables are automatically passed in
# (from .env file) by commandbox-dotenv .
box server start serverConfigFile="$serverConfigFile"
