# Publish Github Release
name: Github Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/create-gh-release-action@v1.5.0
        with:
          # Produced by the build/Build.cfc
          changelog: changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
