name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
  pull_request:
    branches:
      - development

jobs:
  #############################################
  # Tests First baby! We fail, no build :(
  #############################################
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      MODULE_ID: s3sdk
      AWS_DOMAIN: amazonaws.com
      AWS_REGION: us-east-1
    strategy:
      fail-fast: false
      matrix:
        cfengine: [ "lucee@5", "adobe@2016", "adobe@2018", "adobe@2021" ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup Environment For Test Harness
        working-directory: ./test-harness
        run: |
          # Setup .env
          touch .env
          printf "AWS_ACCESS_KEY=${{ secrets.S3SDK_AWS_ACCESS_KEY }}\n" >> .env
          printf "AWS_ACCESS_SECRET=${{ secrets.S3SDK_AWS_ACCESS_SECRET }}\n" >> .env
          printf "AWS_REGION=${{ env.AWS_REGION }}\n" >> .env
          printf "AWS_DOMAIN=${{ env.AWS_DOMAIN }}\n" >> .env
          printf "ENGINE=${{ matrix.cfengine }}\n" >> .env

      - name: Setup CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Install Dependencies
        working-directory: ./test-harness
        run: |
          box install

      - name: Start ${{ matrix.cfengine }} Server
        working-directory: ./test-harness
        run: |
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --noSaveSettings --debug
          curl http://127.0.0.1:60299

      - name: Run Tests
        working-directory: ./test-harness
        run: |
          mkdir tests/results
          box package set testbox.runner="http://localhost:60299/tests/runner.cfm"
          box testbox run --verbose outputFile=tests/results/test-results outputFormats=json,antjunit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-harness/tests/results/**/*.xml
          check_name: "${{ matrix.cfengine }} Test Results"

      - name: Failure Debugging Info
        if: ${{ failure() }}
        working-directory: ./test-harness
        run: |
          box server log serverConfigFile="server-${{ matrix.cfengine }}.json"

      - name: Upload Debugging Info To Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Failure Debugging Info - ${{ matrix.cfengine }}
          path: |
            test-harness/.engine/**/logs/*
            test-harness/.engine/**/WEB-INF/cfusion/logs/*

  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Set Up CommandBox
        uses: elpete/setup-commandbox@v1.0.0

      - name: Install CFFormat
        run: box install commandbox-cfformat

      - name: Run CFFormat
        run: box run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply cfformat changes