name: Test Suites

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false
      S3SDK_AWS_ACCESS_KEY:
        required: true
      S3SDK_AWS_ACCESS_SECRET:
        required: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    env:
      DB_USER: root
      DB_PASSWORD: root
      AWS_DOMAIN: amazonaws.com
      AWS_REGION: us-east-1
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        cfengine:  [ "lucee@5", "adobe@2018", "adobe@2021" ]
        coldboxVersion: [ "^6.0.0" ]
        experimental: [ false ]
        include:
          - cfengine: "adobe@2023"
            coldboxVersion: "^6.0.0"
            experimental: true
          - coldboxVersion: "be"
            cfengine: "lucee@5"
            experimental: true
          - coldboxVersion: "be"
            cfengine: "adobe@2018"
            experimental: true
          - coldboxVersion: "be"
            cfengine: "adobe@2021"
            experimental: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      # - name: Setup Database and Fixtures
      #   run: |
      #     #sudo systemctl start mysql.service
      #     ## Create Database
      #     #mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e 'CREATE DATABASE cbsecurity;'
      #     ## Import Database
      #     #mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < test-harness/tests/resources/cbsecurity.sql

      - name: Setup Environment For Testing Process
        run: |
          # Setup .env
          touch .env
          # ENV
          printf "ENVIRONMENT=development\n" >> .env
          printf "AWS_ACCESS_KEY=${{ secrets.S3SDK_AWS_ACCESS_KEY }}\n" >> .env
          printf "AWS_ACCESS_SECRET=${{ secrets.S3SDK_AWS_ACCESS_SECRET }}\n" >> .env
          printf "AWS_REGION=${{ env.AWS_REGION }}\n" >> .env
          printf "AWS_DOMAIN=${{ env.AWS_DOMAIN }}\n" >> .env
          printf "ENGINE=${{ matrix.cfengine }}\n" >> .env
          printf "COLDBOX_VERSION=${{ matrix.coldboxVersion }}\n" >> .env


      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install Test Harness with ColdBox ${{ matrix.coldboxVersion }}
        run: |
          box install
          cd test-harness
          box package set dependencies.coldbox=${{ matrix.coldboxVersion }}
          box install

      - name: Start ${{ matrix.cfengine }} Server
        run: |
          box server start serverConfigFile="server-${{ matrix.cfengine }}.json" --noSaveSettings --debug
          curl http://127.0.0.1:60299

      - name: Run Tests
        run: |
          mkdir -p test-harness/tests/results
          box testbox run --verbose outputFile=test-harness/tests/results/test-results outputFormats=json,antjunit
          ls -lR test-harness/tests

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-harness/tests/results/**/*.xml
          check_name: "${{ matrix.cfengine }} Test Results"

      - name: Upload Test Results to Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.cfengine }}
          path: |
            test-harness/tests/results/**/*

      - name: Failure Debugging Log
        if: ${{ failure() }}
        run: |
          box server log serverConfigFile="server-${{ matrix.cfengine }}.json"

      - name: Upload Debugging Log To Artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Failure Debugging Info - ${{ matrix.cfengine }}
          path: |
            .engine/**/logs/*
            .engine/**/WEB-INF/cfusion/logs/*

      - name: Slack Notifications
        # Only on failures and NOT in pull requests
        if: ${{ failure() && !startsWith( 'pull_request', github.event_name ) }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coding
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: '${{ github.repository }} tests failed :cry:'
          SLACK_TITLE: ${{ github.repository }} Tests For ${{ matrix.cfengine }} failed
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
